export const TOGGLE_MENU_SIDEBAR = "TOGGLE_MENU_SIDEBAR";
export const CLEAR_MENU_STATE = "CLEAR_MENU_STATE";

export const TOGGLE_CONTENT = "TOGGLE_CONTENT";
export const SELECT_ALL_CONTENT = "SELECT_ALL_CONTENT";
export const CLEAR_CONTENT_SELECTION = "CLEAR_CONTENT_SELECTION";
