export const GET_WORKBOOKS_REQUEST = "workbooks/GET_WORKBOOKS_REQUEST";
export const GET_WORKBOOKS_SUCCESS = "workbooks/GET_WORKBOOKS_SUCCESS";
export const GET_WORKBOOKS_FAILURE = "workbooks/GET_WORKBOOKS_FAILURE";

export const CREATE_WORKBOOK_REQUEST = "workbooks/CREATE_WORKBOOK_REQUEST";
export const CREATE_WORKBOOK_SUCCESS = "workbooks/CREATE_WORKBOOK_SUCCESS";
export const CREATE_WORKBOOK_FAILURE = "workbooks/CREATE_WORKBOOK_FAILURE";

export const DELETE_WORKBOOK_REQUEST = "workbooks/DELETE_WORKBOOK_REQUEST";
export const DELETE_WORKBOOK_SUCCESS = "workbooks/DELETE_WORKBOOK_SUCCESS";
export const DELETE_WORKBOOK_FAILURE = "workbooks/DELETE_WORKBOOK_FAILURE";
