/**
 * Created by sharavan on 06/06/16.
 */
export const data = {
  "1027905" : {
    "name"           : "Analyze Superstore",
    "id"             : "1027905",
    "size"           : 1088355,
    "isFavorite"     : true,
    "usageInfo"      : {
      "hitsTotal"                 : 0,
      "favoritesTotal"            : 0,
      "hitsLastTwelveMonthsTotal" : 0,
      "hitsLastThreeMonthsTotal"  : 0,
      "hitsLastOneMonthTotal"     : 0,
      "subscriptionsTotal"        : 0,
    },
    "ownerId"        : "160907",
    "updatedAt"      : "2014-05-16T13:24:36",
    "displayTabs"    : true,
    "repositoryUrl"  : "AnalyzeSuperstore",
    "defaultViewUrl" : "AnalyzeSuperstore/Overview",
    "projectId"      : "38370",
    "sheetCount"     : 7,
    "defaultViewId"  : "3442244",
    "thumbnailUrl"   : "vizportal/api/rest/v1/workbooks/1027905/thumbnail?1463405076526",
    "hasAlert"       : false,
    "hasExtracts"    : false,
    "downloadUrl"    : "/t/sss/workbooks/AnalyzeSuperstore.twb",
  },
  "1027903" : {
    "name"                  : "Google Analytics",
    "id"                    : "1027903",
    "size"                  : 237618,
    "usageInfo"             : {
      "hitsTotal"                 : 0,
      "favoritesTotal"            : 0,
      "hitsLastTwelveMonthsTotal" : 0,
      "hitsLastThreeMonthsTotal"  : 0,
      "hitsLastOneMonthTotal"     : 0,
      "subscriptionsTotal"        : 0,
    },
    "ownerId"               : "160907",
    "updatedAt"             : "2016-02-16T13:24:25",
    "displayTabs"           : true,
    "repositoryUrl"         : "GoogleAnalytics",
    "defaultViewUrl"        : "GoogleAnalytics/OverallTrends",
    "projectId"             : "38370",
    "sheetCount"            : 2,
    "hasIncrementalExtract" : false,
    "defaultViewId"         : "3442237",
    "thumbnailUrl"          : "vizportal/api/rest/v1/workbooks/1027903/thumbnail?1463405065417",
    "hasAlert"              : false,
    "hasExtracts"           : true,
    "downloadUrl"           : "/t/sss/workbooks/GoogleAnalytics.twb",
  },
  "1027904" : {
    "name"                  : "Executive Salesforce",
    "id"                    : "1027904",
    "size"                  : 846983,
    "usageInfo"             : {
      "hitsTotal"                 : 0,
      "favoritesTotal"            : 0,
      "hitsLastTwelveMonthsTotal" : 0,
      "hitsLastThreeMonthsTotal"  : 0,
      "hitsLastOneMonthTotal"     : 0,
      "subscriptionsTotal"        : 0,
    },
    "ownerId"               : "160907",
    "updatedAt"             : "2016-02-19T13:24:30",
    "displayTabs"           : true,
    "repositoryUrl"         : "ExecutiveSalesforce",
    "defaultViewUrl"        : "ExecutiveSalesforce/SalesSummary",
    "projectId"             : "38370",
    "sheetCount"            : 5,
    "hasIncrementalExtract" : false,
    "defaultViewId"         : "3442239",
    "thumbnailUrl"          : "vizportal/api/rest/v1/workbooks/1027904/thumbnail?1463405070512",
    "hasAlert"              : false,
    "hasExtracts"           : true,
    "downloadUrl"           : "/t/sss/workbooks/ExecutiveSalesforce.twb",
  },
};
