export const data = {
  30013 : {
    "authSetting"                       : "DEFAULT",
    "lastSignIn"                        : "2016-06-08T02:39:54.267Z",
    "groupCount"                        : 1,
    "siteRole"                          : "SiteAdministrator",
    "refreshFailureNotificationEnabled" : true,
    "id"                                : "30013",
    "displayName"                       : "Sharavanth R",
    "username"                          : "shravan@trbvn.com",
    "domainName"                        : "external",
  },
  30014 : {
    "authSetting"                       : "DEFAULT",
    "lastSignIn"                        : "2016-06-08T02:39:54.267Z",
    "groupCount"                        : 1,
    "siteRole"                          : "User",
    "refreshFailureNotificationEnabled" : true,
    "id"                                : "30014",
    "displayName"                       : "BalaSubramanian N",
    "username"                          : "bala@trbvn.com",
    "domainName"                        : "external",
  },
  30015 : {
    "authSetting"                       : "DEFAULT",
    "lastSignIn"                        : "2016-06-08T02:39:54.267Z",
    "groupCount"                        : 1,
    "siteRole"                          : "User",
    "refreshFailureNotificationEnabled" : true,
    "id"                                : "30015",
    "displayName"                       : "Avinesh Ram",
    "username"                          : "falcon@trbvn.com",
    "domainName"                        : "external",
  }
};
