export const CONTENT_REQUEST = "CONTENT_REQUEST";
export const CONTENT_SUCCESS = "CONTENT_SUCCESS";
export const CONTENT_FAILURE = "CONTENT_FAILURE";

export const TEMPLATE_CREATE_REQUEST = "TEMPLATE_CREATE_REQUEST";
export const TEMPLATE_CREATE_SUCCESS = "TEMPLATE_CREATE_SUCCESS";
export const TEMPLATE_CREATE_FAILURE = "TEMPLATE_CREATE_FAILURE";
export const TEMPLATE_DELETE_REQUEST = "TEMPLATE_DELETE_REQUEST";
export const TEMPLATE_DELETE_SUCCESS = "TEMPLATE_DELETE_SUCCESS";
export const TEMPLATE_DELETE_FAILURE = "TEMPLATE_DELETE_FAILURE";

export const TOGGLE_CONTENT = "TOGGLE_CONTENT";
export const SELECT_ALL_CONTENT = "SELECT_ALL_CONTENT";
export const CLEAR_CONTENT_SELECTION = "CLEAR_CONTENT_SELECTION";
