/**
 * Created by sharavan on 28/06/16.
 */
export const EDITOR_REQUEST = "EDITOR_REQUEST";
export const EDITOR_SUCCESS = "EDITOR_SUCCESS";
export const EDITOR_FAILURE = "EDITOR_FAILURE";

export const TEMPLATE_EDIT_REQUEST = "TEMPLATE_EDIT_REQUEST";
export const TEMPLATE_EDIT_SUCCESS = "TEMPLATE_EDIT_SUCCESS";
export const TEMPLATE_EDIT_FAILURE = "TEMPLATE_EDIT_FAILURE";
