export const SORT_FILTER = "SORT_FILTER";

export const SET_FILTER_DTMOD_START = "SET_FILTER_DTMOD_START";
export const SET_FILTER_DTMOD_END = "SET_FILTER_DTMOD_END";
export const SET_FILTER_OWNER = "SET_FILTER_OWNER";
export const SET_FILTER_IS_RECENT = "SET_FILTER_IS_RECENT";
export const SET_FILTER_IS_STARRED = "SET_FILTER_IS_STARRED";
export const CLEAR_FILTER_STATE = "CLEAR_FILTER_STATE";
